version: '3.8'

services:
  atlas-txn-sender:
    build: .
    ports:
      - '7998:7998' # Datadog statsd port
    environment:
      - RPC_URL=https://devnet.helius-rpc.com/?api-key=c8405459-a909-4d08-a58e-ba28165268ab
      - GRPC_URL=https://grpc-takehome-devnet.helius-rpc.com:443
      - X_TOKEN=826dfa33-2a09-4edd-8a49-7a77c0e6fb3b
    volumes:
      - .:/app
    restart: unless-stopped
