- name: atlas-txn-sender setup
  become: yes
  hosts: all
  vars:
    user: ubuntu
    service: atlas-txn-sender
    rpc_url: https://devnet.helius-rpc.com/?api-key=c8405459-a909-4d08-a58e-ba28165268ab
    grpc_url: https://grpc-takehome-devnet.helius-rpc.com:443
    x_token: 826dfa33-2a09-4edd-8a49-7a77c0e6fb3b
    datadog_api_key: 6eec17f701aa475ade25ee728d3cd25d
    datadog_site: us5.datadoghq.com
    datadog_config:
      dogstatsd_port: 7998
      use_dogstatsd: true
      logs_enabled: true
      tags:
        - "staked:{{staked|default('false')}}"
        - 'env:prod'
        - 'service:atlas_txn_sender'
        - 'network:mainnet'
        - 'region:{{region}}'
        - "fleet_type:{{fleet_type|default('atlas')}}"
  tasks:
    - name: Execute datadog setup
      include_role:
        name: datadog-setup
    - name: Install haproxy
      include_role:
        name: haproxy-setup
    - name: Install rust
      include_role:
        name: install-rust
    - name: Execute atlas-txn-sender setup
      include_role:
        name: atlas-txn-sender
