- name: atlas-txn-sender setup
  become: yes
  hosts: all
  vars_files:
    - secrets.yml
  vars:
    user: ubuntu
    service: atlas-txn-sender
    rpc_url: '{{ vault_rpc_url }}'
    grpc_url: https://grpc-takehome-devnet.helius-rpc.com:443
    x_token: '{{ vault_x_token }}'
    datadog_api_key: '{{ vault_datadog_api_key }}'
    datadog_site: us5.datadoghq.com
    datadog_config:
      dogstatsd_port: 7998
      use_dogstatsd: true
      logs_enabled: true
      tags:
        - "staked:{{staked|default('false')}}"
        - 'env:prod'
        - 'service:atlas_txn_sender'
        - 'network:mainnet'
        - 'region:{{region}}'
        - "fleet_type:{{fleet_type|default('atlas')}}"
  tasks:
    - name: Execute datadog setup
      include_role:
        name: datadog-setup
    - name: Install haproxy
      include_role:
        name: haproxy-setup
    - name: Install rust
      include_role:
        name: install-rust
    - name: Execute atlas-txn-sender setup
      include_role:
        name: atlas-txn-sender
